Algoritmo "Idades"

Var

   nome1, nome2 : caractere
   i1, i2 : inteiro
   media : real

Inicio

      nome1 <- "Maria Silva"
      i1 <- 19
      nome2 <- "Joao Melo"
      i2 <- 20
      media <- (i1 + i2) / 2
      
      escreval ("Dados da primeira pessoa:")
      escreval ("Nome: ", nome1)
      escreval ("Idade: ", i1)
      escreval ("Dados da segunda pessoa:")
      escreval ("Nome: ", nome2)
      escreval ("Idade: ", i2)
      escreval ("A idade média de Maria Silva e Joao Melo é de ", media:4:1, " anos")

Fimalgoritmo